spring:
  application:
    name: restaurant Management System

  messages:
    basename: i18n/messages

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr

  # الـ data لازم تبدأ من نفس مستوى datasource و messages
  data:
    redis:
      host: localhost
      port: 6379
      password: "123456"
      client-name: "my-redis-client"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# إعدادات الـ Token والـ Server زي ما هي
token:
  secret: fnkwfkteFgswffe5e64f78fej#&$*)#Hpdffe7efEERedsR
  time: 24h

server:
  port: 8081